server:
  port: 8080

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/springbootdb' //change your URL
    username: 'change your username'
    password: 'change your password'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG

aws:
  accessKey: 'use your access key'
  secretKey: 'use your secret key'
  region: 'us-east-1'
  s3:
    bucketName: 'use your bucket name'




